### PR TITLE
Eslint7 compatibility - fixes #19

### LINKED ISSUE #19: no-arrow-functions - Fix has invalid range
ESLint version 8.7.0,
eslint-plugin-cucumber version 1.4.0

When using the no-arrow-functions I get the following error:

``` 
AssertionError [ERR_ASSERTION]: Fix has invalid range: {
  "range": [
    null,
    null
  ],
  "text": "function() "
}
    at assertValidFix (\node_modules\eslint\lib\linter\report-translator.js:125:9)
    at normalizeFixes (\node_modules\eslint\lib\linter\report-translator.js:200:5)
    at \node_modules\eslint\lib\linter\report-translator.js:364:49
    at Object.report (\node_modules\eslint\lib\linter\linter.js:1050:41)
    at CallExpression (\node_modules\eslint-plugin-cucumber\lib\rules\no-arrow-functions.js:101:19)
    at ruleErrorHandler (\node_modules\eslint\lib\linter\linter.js:1079:28)
    at \node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

### PR DESCRIPTION
**Pull request by sgtwilko**
This updates the no-arrow-functions rule to add ESLint7 compatibility.  This resolves issue #19 

I've also bumped the ESLint version to 8.9, which has updated rule testing which requires checking the output from the rule matches the expected values.

### CODE REVIEW

**Comment by sgtwilko** [comment]
Hey @darrinholst great project, but are you still maintaining it?

**Comment by darrinholst** [comment]
> Hey @darrinholst great project, but are you still maintaining it?

I can merge it. There are no breaking changes?

**Comment by sgtwilko** [comment]
@darrinholst 
Hiya, 
Not that I'm aware of, without this change the rule just won't work on ESLint7+.

**Comment by sgtwilko** [comment]
Just spotted the conflict (wasn't there when I submitted, I presume you've merged some other PRs), do you need me to resolve?

**Comment by darrinholst** [comment]
> Just spotted the conflict (wasn't there when I submitted, I presume you've merged some other PRs), do you need me to resolve?

I'll fix it

**Comment by darrinholst** [comment]
resolved and merged locally

**Comment by sgtwilko** [comment]
Thank you sir

**Pull request closed without merging**
